### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by iFlameing**
#1 EDIT README.

### CODE REVIEW

**Review by rava-dosa — APPROVED** [review]
Good work

**Comment by rava-dosa** [comment]
Can you send another pr as my readme.md is looking really improper ?

**Comment by iFlameing** [comment]
I can as i do not know the exact process for installation and library used
if you send me something about this I can improve my pull request

**Comment by rava-dosa** [comment]
If you see carefully you will see library used such as opencv,boost, etc. Search how to install these libraries and send a new pr

**Pull request merged**
